# Generated by Django 4.2.9 on 2024-12-04 09:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UsersProfiles',
            fields=[
                ('primary_key', models.AutoField(primary_key=True, serialize=False)),
                ('profile_unique_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('profile_phone', models.CharField(blank=True, default='', max_length=9000)),
                ('profile_photo', models.CharField(blank=True, default='/profiles/user_profile.png', max_length=600, null=True)),
                ('profile_gender', models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE')], max_length=100, null=True)),
                ('profile_type', models.CharField(blank=True, choices=[('REGISTERD_USER', 'REGISTERD_USER'), ('ADMIN', 'ADMIN'), ('MANAGEMENT', 'MANAGEMENT')], default='REGISTERD_USER', max_length=9000, null=True)),
                ('profile_is_active', models.BooleanField(db_index=True, default=True)),
                ('profile_created_date', models.DateField(auto_now_add=True)),
                ('profile_has_been_verified', models.BooleanField(default=True)),
                ('profile_user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': '01.USER PROFILES',
                'db_table': 'user_profiles',
                'ordering': ['-primary_key'],
            },
        ),
        migrations.CreateModel(
            name='SavePasswordRequestUsers',
            fields=[
                ('primary_key', models.AutoField(primary_key=True, serialize=False)),
                ('save_pswd_token', models.CharField(default=None, editable=False, max_length=300)),
                ('save_pswd_is_used', models.BooleanField(default=False)),
                ('save_pswd_is_active', models.BooleanField(default=True)),
                ('save_pswd_expiration_time', models.DateTimeField()),
                ('save_pswd_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': '03.SAVE PASSWORD REQUESTS',
                'db_table': 'users_save_password_request',
                'ordering': ['-primary_key'],
            },
        ),
        migrations.CreateModel(
            name='ForgotPasswordRequestUsers',
            fields=[
                ('primary_key', models.AutoField(primary_key=True, serialize=False)),
                ('request_token', models.CharField(default=None, editable=False, max_length=300)),
                ('request_is_used', models.BooleanField(default=False)),
                ('request_is_active', models.BooleanField(default=True)),
                ('request_expiration_time', models.DateTimeField()),
                ('request_created_date', models.DateTimeField(auto_now=True)),
                ('request_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': '02.FORGOT PASSWORD REQUESTS',
                'db_table': 'users_forgot_password_request',
                'ordering': ['-primary_key'],
            },
        ),
        migrations.CreateModel(
            name='ActivateAccountTokenUsers',
            fields=[
                ('primary_key', models.AutoField(primary_key=True, serialize=False)),
                ('token_token', models.CharField(default=None, editable=False, max_length=300)),
                ('token_is_used', models.BooleanField(default=False)),
                ('token_is_active', models.BooleanField(default=True)),
                ('token_created_date', models.DateTimeField(auto_now_add=True)),
                ('token_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='token_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': '04.ACTIVATE ACCOUNT TOKEN',
                'db_table': 'users_activate_account_token',
                'ordering': ['-primary_key'],
            },
        ),
    ]
